In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn. tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn. metrics import confusion_matrix

df = pd.read_csv(r"C:\Users\Santosh Agasti\Downloads\heart.csv")


In [3]:
print("First 5 Rows:")
print(df.head())

print("\nDataset Info:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

First 5 Rows:
   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0  

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol  

In [4]:
X = df.drop("target", axis=1)
y = df["target"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [6]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
log_model = LogisticRegression()

log_model.fit(X_train, y_train)

log_pred = log_model.predict(X_test)

log_accuracy = accuracy_score(y_test, log_pred)


In [9]:

print("Logistic Regression Results:")

print("Accuracy:", log_accuracy)

print("\nClassification Report:")
print(classification_report(y_test, log_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, log_pred))

Logistic Regression Results:
Accuracy: 0.7951219512195122

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.72      0.78       102
           1       0.76      0.87      0.81       103

    accuracy                           0.80       205
   macro avg       0.80      0.79      0.79       205
weighted avg       0.80      0.80      0.79       205


Confusion Matrix:
[[73 29]
 [13 90]]


In [10]:
knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

knn_pred = knn_model.predict(X_test)

knn_accuracy = accuracy_score(y_test, knn_pred)


print("KNN Results:")

print("Accuracy:", knn_accuracy)

print("\nClassification Report:")
print(classification_report(y_test, knn_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, knn_pred))

KNN Results:
Accuracy: 0.8341463414634146

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.77      0.82       102
           1       0.80      0.89      0.84       103

    accuracy                           0.83       205
   macro avg       0.84      0.83      0.83       205
weighted avg       0.84      0.83      0.83       205


Confusion Matrix:
[[79 23]
 [11 92]]


In [11]:
dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_pred)
print("Decision Tree Results:")
print("Accuracy:", dt_accuracy)

print("\nClassification Report:")
print(classification_report(y_test, dt_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, dt_pred))


Decision Tree Results:
Accuracy: 0.9853658536585366

Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       102
           1       1.00      0.97      0.99       103

    accuracy                           0.99       205
   macro avg       0.99      0.99      0.99       205
weighted avg       0.99      0.99      0.99       205


Confusion Matrix:
[[102   0]
 [  3 100]]


In [13]:

print("MODEL ACCURACY COMPARISION")


print("Logistic Regression Accuracy :", log_accuracy)
print("KNN Accuracy                 :", knn_accuracy)
print("Decision Tree Accuracy       :", dt_accuracy)


MODEL ACCURACY COMPARISION
Logistic Regression Accuracy : 0.7951219512195122
KNN Accuracy                 : 0.8341463414634146
Decision Tree Accuracy       : 0.9853658536585366


In [18]:

from sklearn.metrics import accuracy_score, f1_score
import pandas as pd

log_accuracy = accuracy_score(y_test, log_pred)
knn_accuracy = accuracy_score(y_test, knn_pred)
dt_accuracy = accuracy_score(y_test, dt_pred)

log_f1 = f1_score(y_test, log_pred)
knn_f1 = f1_score(y_test, knn_pred)
dt_f1 = f1_score(y_test, dt_pred)


results = pd.DataFrame({
    'Algorithm': [
        'Logistic Regression',
        'KNN',
        'Decision Tree'
    ],
    
    'Accuracy': [
        f'{log_accuracy*100:.0f}%',
        f'{knn_accuracy*100:.0f}%',
        f'{dt_accuracy*100:.0f}%'
    ],
    
    'F1 Score': [
        round(log_f1, 2),
        round(knn_f1, 2),
        round(dt_f1, 2)
    ]
})


print("COMPARING RESULTS:")


print(results)



best_accuracy = results['Accuracy'].max()

print("\nBest Performing Algorithm:")
print(results.loc[results['Accuracy'] == best_accuracy])

COMPARING RESULTS:
             Algorithm Accuracy  F1 Score
0  Logistic Regression      80%      0.81
1                  KNN      83%      0.84
2        Decision Tree      99%      0.99

Best Performing Algorithm:
       Algorithm Accuracy  F1 Score
2  Decision Tree      99%      0.99
